import type { Reward } from './types';

export const HARDCODED_REWARDS: Reward[] = [
  {
    id: 'brooks-01',
    brand: 'Brooks',
    title: '20% off any Brooks shoe',
    description: 'Valid on full-price footwear at Brooks Running online store.',
    paceCost: 75,
    tier: 'entry',
    status: 'available',
    brandColor: '#0066CC',
    brandInitial: 'B',
    valueLabel: '20% off',
    expiresLabel: 'Limited offer',
    category: 'gear',
  },
  {
    id: 'sis-01',
    brand: 'Science in Sport',
    title: 'Energy gel sample pack (6 gels)',
    description: 'Try the full SiS GO Isotonic gel range — free shipping included.',
    paceCost: 50,
    tier: 'entry',
    status: 'available',
    brandColor: '#E63B2E',
    brandInitial: 'S',
    valueLabel: '6 free gels',
    category: 'nutrition',
  },
  {
    id: 'garmin-01',
    brand: 'Garmin Connect',
    title: '3-month Garmin Connect premium trial',
    description: 'Advanced training analytics, recovery advisor, and performance stats.',
    paceCost: 150,
    tier: 'mid',
    status: 'available',
    brandColor: '#007CC3',
    brandInitial: 'G',
    valueLabel: '3 months free',
    category: 'tech',
  },
  {
    id: 'on-01',
    brand: 'On Running',
    title: '15% off On Running apparel',
    description: 'Exclusive Runivo runner discount on the On Running online store.',
    paceCost: 120,
    tier: 'mid',
    status: 'coming_soon',
    brandColor: '#1A1A1A',
    brandInitial: 'O',
    valueLabel: '15% off',
    category: 'gear',
  },
  {
    id: 'race-01',
    brand: 'Running Events',
    title: 'Free 10K race entry',
    description: 'Entry to a partner running event in your city. Dates announced monthly.',
    paceCost: 300,
    tier: 'premium',
    status: 'coming_soon',
    brandColor: '#2D7D46',
    brandInitial: 'R',
    valueLabel: 'Free entry',
    category: 'events',
  },
  {
    id: 'coros-01',
    brand: 'COROS',
    title: 'COROS PACE 3 GPS watch',
    description: 'Earn enough PACE and claim a COROS PACE 3. Serious runners only.',
    paceCost: 800,
    tier: 'premium',
    status: 'coming_soon',
    brandColor: '#C41E3A',
    brandInitial: 'C',
    valueLabel: '$279 value',
    category: 'tech',
  },
];
