-- Training plans: stores Claude-generated training plans per user
CREATE TABLE IF NOT EXISTS training_plans (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  goal         TEXT        NOT NULL,
  goal_race_date DATE,
  weeks_total  INTEGER     NOT NULL DEFAULT 4,
  week_current INTEGER     NOT NULL DEFAULT 1,
  status       TEXT        NOT NULL DEFAULT 'active'
                           CHECK (status IN ('active', 'completed', 'abandoned')),
  plan_data    JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_training_plans_user_status
  ON training_plans(user_id, status);

ALTER TABLE training_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "training_plans_owner"
  ON training_plans FOR ALL
  USING (auth.uid() = user_id);

-- Plan adaptations: weekly adaptation notes generated by Claude
CREATE TABLE IF NOT EXISTS plan_adaptations (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id          UUID        NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
  week_number      INTEGER     NOT NULL,
  adaptation_note  TEXT,
  adapted_sessions JSONB,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_plan_adaptations_plan_id
  ON plan_adaptations(plan_id);

ALTER TABLE plan_adaptations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "plan_adaptations_owner"
  ON plan_adaptations FOR ALL
  USING (
    plan_id IN (
      SELECT id FROM training_plans WHERE user_id = auth.uid()
    )
  );

-- Trigger to keep updated_at current on training_plans
CREATE OR REPLACE FUNCTION update_training_plan_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER training_plans_updated_at
  BEFORE UPDATE ON training_plans
  FOR EACH ROW EXECUTE FUNCTION update_training_plan_timestamp();
